### ISSUE TITLE
Give chess_db compatible offset back in scout json output

### ISSUE THREAD

**Issue by gbtami** [mcostalba/scoutfish#29]
Maybe sending an UCI option to scoutfish can change it to create 8byte aligned offsets on output.
See https://github.com/mcostalba/chess_db/issues/28

**Comment by mcostalba** [comment]
Compatible to what? Can you please better explain what you are thinking about and why?

**Comment by gbtami** [comment]
Game offset values produced by chess_db "find" output and by scoutfish "scout" output are different for the same games of a .pgn file.
https://github.com/mcostalba/chess_db/blob/master/parser/parser.cpp#L257
vs.
https://github.com/mcostalba/scoutfish/blob/master/src/parser.cpp#L108

Chess UI programs wants to provide game querying/filtering not just on opening positions (using chess_db parser) or special queries (using scoutfish) but on game header tags too. To provide this effectively we have to create another database (sql/nosql) built from game header tags and game offsets as primary key/index. But if chess_db and scoutfish gives us different offsets for the same games as output it's hard to combine these offsets to game header database records.

**Comment by sshivaji** [comment]
Briefly chiming in to talk about the workflow of UI programs (basically I am repeating what @gbtami is saying but from an end user angle), its worth a brainstorm in my opinion. People typically search for things like "find me all Carlsen games where he used 2 bishops vs bishop and knight, what is the winning percentage%, how does this compare to other strong players"?

The workflows can look like:

1. Sending game_offsets to scoutfish: Query parser for header text (all "Carlsen" games) -> get a list of game_ids -> send these game_ids over to scoutfish for pattern search on 2 bishops vs bishop and Knight -> get results. This workflow is currently NOT supported by scoutfish, it can be supported if game offset_ids can be part of the query.

2. Query Scoutfish for all games of 2 bishops vs Bishop and Knight ->  get all game offsets -> get all Carlsen game offsets from the header data -> discard all offsets which are not in the Carlsen set -> present results to user

In both of the above workflows, the game offset and the headers are important. I can use python-chess's scan_headers but in that case the offset by python-chess should match with scoutfish and chess_db.

Proposals:

1. Support get_all_headers in book make api. I sent a pull request with this enabled, I can re-send it. I know you rejected it at the time due to the need to focus on position and pattern search and not headers. However, it can cover this gap.

2. Can you return game_number in addition to offsets? That would mean that if we use any other 3rd party tool to generate headers, the game_number is likely to be correct. Then we can support searches such as find all patterns in game_number 2, 3, 4, 1000 and or get game_numbers back so that we know exactly which games are the relevant ones.

I think a variant of 1 is better for performance as scoutfish and chess_db are much faster than any other tools at this point.

**Comment by mcostalba** [comment]
I am sorry but text parsing at the moment is up to higher level tools. I
don't think I will change api regarding this point.

Perhaps in the future, when I will see a real case in a UI tool I will
change my mind, but at the moment is all just speculative discussion. It is
OK for me to discuss possible cases or user scenarios just for the shake of
it. But code will change when there will be a real case.

**Comment by sshivaji** [comment]
Let me lay out a simple real use case:

1. Search for all Carlsen games where he won with 2 Bishops against Bishop and Knight. This is NOT possible now because the offset numbers are not consistent. However, what I can do is to see how bad the offset numbers are with scan_headers in python-chess and see if I can make this work somehow.

We dont have to support text parsing at all, how about just returning game numbers in the output in addition to game offsets? I think that should be easy.

If you want the case to be more real, I will try out the search above and come back with my findings before we support returning game numbers in addition to game_offsets. In fact, to drive the point home, I will show the issue in real UI so that you can see it :)

**Comment by mcostalba** [comment]
@gbtami I understand what you mean, but the 2 offsets differ only because chess_db one is gameOfs >> 3, this is due to the need of storing in polyglot 'learn' field. In scoutfish we don't have this limitation and introduce it artificially it seems to me a hack.

What you could to is to store in your DB the scoutfish offset, that is the complete one, then get the other by >> 3. 

Another, option is just to store the chess_db offset and use that also for scoutfish , it will work the same because of the lookup logic. Anyhow I would wait to have a working example of user case to further proceed on it.

**Comment by gbtami** [comment]
After rethinking this offset issue again I'v got the same conclusion. Thx for your help in rethinking! Sometimes trivial solutions comes last to my mind :)
