### ISSUE TITLE
False match returned by scout

### ISSUE THREAD

**Issue by gbtami** [mcostalba/scoutfish#43]
[Event "Local Event"]
[Site "Local Site"]
[Date "2017.02.06"]
[Round "1"]
[White "bt"]
[Black "Guest"]
[Result "1/2-1/2"]
[ECO "C23"]
[TimeControl "300+0"]
[WhiteClock "0:04:17.098"]
[BlackClock "0:04:44.391"]
[PlyCount "20"]

1. e4 e5 2. Bc4 Bc5 3. Nf3 Nf6 4. d3 d6 5. Be3 Be6 6. Nc3 Nc6 7. Qd2 Qd7 8. Ke2
Ke7 9. Rhe1 Rhe8 10. h3 h6 1/2-1/2

```
tamas@tami:~/scoutfish$ src/scoutfish scout ../white-move-Rae1.scout '{"white-move": "Rae1"}'
{
    "moves": 20,
    "match count": 1,
    "moves/second": 10000,
    "processing time (ms)": 2,
    "matches":
    [
        { "ofs": 0, "ply": [17] }
    ]
}
```

I suggest to use long algebraic notation in "white-move" and "black-move" rules instead of SAN to prevent such false matches.

**Comment by mcostalba** [comment]
This is done on purpose, if you see:

https://github.com/mcostalba/scoutfish/blob/master/src/scout.cpp#L368

Here the move is coded as (piece, to_square), so that Nf3 picks the first knight move in f3 and does not matter where the knight comes from: algebraic notation forces to explicit the from square but IMO is too restrictive.

Eventually I will add a disambiguation flag, to correctly handle cases where disambiguation is given but without being too restrictive on all the others.

**Comment by gbtami** [comment]
You are right. Fixing this SAN issue is far better than restricting move rules. Btw. what do you think to add support to "?" as joker char in place of piece/file/rank to add more flexibility to move rules?
