### ISSUE TITLE
Does imbalance support multiple queens?

### ISSUE THREAD

**Issue by rozim** [mcostalba/scoutfish#47]
I want to find games where one side has 2 Q's and the other side has a Q and 2 R's.

I tried this:
./scoutfish scout ./mega-filtered.scout '{ "imbalance": "QQvQRR" }'

and spot checked one result and the game had a Q vs 2 R's, but not what I wanted 
(QQ vs QRR).

**Comment by gbtami** [comment]
This is because "imbalance" means: difference in material. In this case this is queen vs rook+rook.
Unfortunately scoutfish has no rule to express that one side has at least two queens.

To demonstrate the query works as expected here is one hit from enormous.pgn using pychess
[http://i.imgur.com/LicU4Fl.png](http://i.imgur.com/LicU4Fl.png)

**Comment by rozim** [comment]
Ah, QED, I get it.
Thanks for quick reply.
WAI.
- Dave
