### ISSUE TITLE
Search for exact FEN

### ISSUE THREAD

**Issue by mcostalba** [mcostalba/scoutfish#6]
This is not a book, so search cannot be immediate, but anyhow is a nice to have, for instance to search all the games with a specific ECO opening (ECO to FEN mapping is up to the UI tool).

**Comment by sshivaji** [comment]
This is actually quite useful!

Comment on ECO: ECO is less popular these days, FEN is ideal. ECO was invented in the 60s and its too narrow/compressed for modern chess. 

On to the more important thing:

Professionals and Amateur tournament players typically do a lot of manual work. They lookup a position and manually spend hours looking over the games for plans and ideas. It is necessary to get a competitive edge over others digging deep into a position to win games. People often want to know what idea to try that can confuse opponents and give chances for victory due to the complex nature of the position (be it tactical or positional).

I foresee that supporting position search and augmenting it with typical themes and ideas can be well automated with scoutfish. 

Example queries that can be supported by position:

1. Find all games from a position where white won with a kingside attack.
2. Find all games from a position where white won due to moving pawns on the queenside. How did he score compared to kingside play?

**Comment by mcostalba** [comment]
Indeed full fen is just a special case of sub-fen!

I have pushed some update to the README to document it...

**Comment by mcostalba** [comment]
It's already done by sub-fen: I think we can close also this one.
